FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y unzip bash nano python3 && \
    apt-get clean

# Create a non-root user
RUN useradd -ms /bin/bash ctfplayer
USER ctfplayer
WORKDIR /home/ctfplayer

# Copy challenge files
COPY --chown=ctfplayer:ctfplayer . .

# Set up entrypoint
CMD ["/bin/bash"]
